### ISSUE TITLE
Can't create RouteTable

### ISSUE THREAD

**Issue by wilhelmi** [crossplane-contrib/provider-jet-aws#184]
Failed to create a RouteTable, can't find a combination that works.

```yaml
        apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
        kind: RouteTable
        spec:
          forProvider:
            route:
             - cidrBlock: "0.0.0.0/0"
                carrierGatewayId: null
                destinationIpv6CidrBlock: null
                destinationPrefixListId: null
                egressOnlyGatewayId: null
                instanceId: null
                ipv6CidrBlock: null
                localGatewayId: null
                natGatewayId: null
                networkInterfaceId: null
                transitGatewayId: null
                vpcEndpointId: null
                vpcPeeringConnectionId: null
      patches:
        - fromFieldPath: status.gatewayId
          toFieldPath: spec.forProvider.route[0].gatewayId
```

Crossplane 1.7.0
jet-aws 0.4.0-preview

Error message:

```
Incorrect attribute value type: Inappropriate value for attribute
"route": element 0: attributes "carrier_gateway_id",
"destination_prefix_list_id", "egress_only_gateway_id", "gateway_id",
"instance_id", "ipv6_cidr_block", "local_gateway_id", "nat_gateway_id",
"network_interface_id", "transit_gateway_id", "vpc_endpoint_id", and
"vpc_peering_connection_id" are required.: File name: main.tf.json
```

Gateway Id is patched in to the correct value.

Reference to potentially relevant TF issues:
https://github.com/hashicorp/terraform-provider-aws/issues/8786#issuecomment-496935442
https://stackoverflow.com/questions/69689262/inappropriate-value-for-attribute-route-element-0-attributes
