### ISSUE TITLE
AWS instances not recreated

### ISSUE THREAD

**Issue by waldner** [crossplane-contrib/provider-jet-aws#205]
I wanted to test the convergence behavior, so I created an AWS instances with the following YAML:

```
apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: Instance
metadata:
  name: crossplane-instance
spec:
  forProvider:
    region: eu-west-1
    ami: ami-0a10fe11f3e1bf41e
    instanceType: t2.micro
    keyName: mykey
  providerConfigRef:
    name: aws-provider-config
```

The creation was fine. I terminated the instance from the AWS console, and crossplane doesn't recreate it with this error:

```
    - lastTransitionTime: "2022-06-02T11:45:18Z"
      message: 'create failed: cannot apply: apply failed: error collecting instance settings: error creating resource: iops attribute not supported for root_block_device with volume_type gp2: : File name: main.tf.json'
      reason: ReconcileError
      status: "False"
      type: Synced
```

Indeed, `main.tf.json` has the following:

```
"root_block_device":[{"iops":100,"volume_size":10,"volume_type":"gp2"}]
```

and the `Instance` spec also:

```
      rootBlockDevice:
      - iops: 100
        volumeSize: 10
        volumeType: gp2
```

so it looks like it was incorrectly backfilled after creation? Any help appreciated.
